name: flutter_icon_snackbar
description: Flutter icon snackbar | Animated snackbar with icons | Easier snackbar over native
homepage: https://github.com/GiYeongUM
repository: https://github.com/GiYeongUM/flutter_icon_snackbar
version: 1.2.0

environment:
  sdk: '>=2.17.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  icon_animated: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
